variables:
  ARM_PASS: $(adminpass)

trigger:
- none

pool:
  vmImage: 'windows-latest'

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.network/azure-bastion/'
# 'quickstarts/microsoft.compute/vm-simple-windows'
#quickstarts/microsoft.compute/vm-simple-windows/
#microsoft.network/vnet-to-vnet/azuredeploy.parameters.json
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'ARMME'
    subscriptionId: 'a5c8cea5-e30c-4a46-9126-efb149669eec'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipelinesPIETER-rg'
    location: 'westeurope'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-bastionHostName mytestPBAST123456'
    #-administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'

